name: CI

on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master
      - beta

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: lint
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck@latest &&
          $HOME/go/bin/staticcheck &&
          make vet

  test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         go:
           - "1.18"
           - "1.17"
           - "1.16"
           - "1.15"
           - "1.14"
           - "1.13"
     name: "Test: go v${{ matrix.go }}"
     steps:
       - uses: actions/checkout@v2
       - name: Setup go
         uses: actions/setup-go@v3
         with:
           go-version: ${{ matrix.go }}
       - name: Start stripe-mock
         run: docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock && sleep 5
       - name: Test
         run: make test &&
              make bench &&
              make check-api-clients
